version: '2.1'

networks:
  monitor-net:
    driver: bridge


services:

  portainer:
    image: portainer/portainer
    container_name: portainer-app
    command: --templates http://templates/templates.json 
    networks:
      - monitor-net
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  postgres-pgadmin:
    image: wnameless/postgresql-phppgadmin
    container_name: postgres-pgadmin
    restart: unless-stopped
    networks:
      - monitor-net:
    ports:
      - "49060:22"
      - "49061:80"
      - "49062:5432"
    labels:
      org.label-schema.group: "monitoring"
      
  jupyter-notebook:
    image: jupyter/datascience-notebook
    container_name: jupyter_notebook
    volumes:
      - /home/jaber/jupyter notebook/work:/home/jovyan/work
    networks:
      - monitor-net
    restart: unless-stopped
    ports:
      - "8888:8888"
    labels:
      org.label-schema.group: "monitoring"
  
